const HOMES = 'HOME';
const SUCCESS_ONBOARD = 'SUCCESS_ONBOARD';
const OTP_VERIFICATION = 'OTP_VERIFICATION';
const REGISTER = 'REGISTER';

export const SCREENS = {
  HOMES,
  REGISTER,
  SUCCESS_ONBOARD,
  OTP_VERIFICATION,
};
